# Generated by Django 3.0.3 on 2020-05-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
